# 파이토치 기초

## 텐서

In [1]:
import torch

In [4]:
# 텐서 생성
print(torch.tensor([1,2,3]))
print(torch.Tensor([[1,2,3],[4,5,6]]))
print(torch.LongTensor([1,2,3]))
print(torch.FloatTensor([1,2,3]))

tensor([1, 2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1, 2, 3])
tensor([1., 2., 3.])


In [7]:
# 텐서 속성
tensor = torch.rand(1,2) # 평균이 1인 정규분포를 따르는 랜덤 변수를 2개 만들어라
print(tensor)
print(tensor.shape) # [[0.0171, 0.9694]] 1, 2
print(tensor.dtype)
print(tensor.device) # gpu로 tensor를 보내줘야 함


tensor([[0.0171, 0.9694]])
torch.Size([1, 2])
torch.float32
cpu


In [9]:
# 차원 변환
tensor = torch.rand(1,8) # 8개
print(tensor)
print(tensor.shape)

tensor = tensor.reshape(2,-1) # reshape할 때 개수만 맞으면 돼. 근데 2,-1은 앞에는 2개 두고 -1은 나머지 알아서
print(tensor)
print(tensor.shape)

tensor([[0.5451, 0.1135, 0.0337, 0.6665, 0.1254, 0.7427, 0.7100, 0.4436]])
torch.Size([1, 8])
tensor([[0.5451, 0.1135, 0.0337, 0.6665],
        [0.1254, 0.7427, 0.7100, 0.4436]])
torch.Size([2, 4])


In [12]:
# 자료형
tensor = torch.rand((3,3), dtype=torch.float64) # torch.float로 하면 torch.float32가 default
print(tensor)

tensor([[0.1408, 0.4121, 0.7263],
        [0.2095, 0.8709, 0.8770],
        [0.8548, 0.8990, 0.9920]], dtype=torch.float64)


In [17]:
# device 설정 (cpu, gpu)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
cpu_tensor = torch.FloatTensor([1,2,3])
gpu_tensor = torch.cuda.FloatTensor([1,2,3]) # 만들 때 cuda를 넣어주거나
tensor = torch.rand((1,1), device = device) # device를 지정해주거나 (중요)
tensor_2 = torch.rand((1,1)).to(device) # .to(device)를 해주면 됨! (매우 중요!!)
print(device)
print(cpu_tensor)
print(gpu_tensor)
print(tensor)
print(tensor_2)

cuda
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([[0.7380]], device='cuda:0')
tensor([[0.8292]], device='cuda:0')


In [21]:
# device 변환
tensor_2 = tensor_2.to('cpu') # 저장을 해줘야 돼
print(tensor_2.device)

cpu


## NumPy
CPU에서 Tensor를 다루는데 최적화된 라이브러리

CPU에서는 NumPy 관련 문법, GPU에서는 PyTorch 문법

둘이 비슷함

In [23]:
import numpy as np

In [28]:
ndarray = np.array([1,2,3], dtype=np.uint8) # n dimension array. CPU, NumPy형태의 array
print(ndarray)
print(torch.tensor(ndarray).device) # torch형태로 바꾸고 싶을 때. gpu 안보내면 아직 cpu
print(torch.from_numpy(ndarray).device) # CPU에서의 PyTorch Tensor

[1 2 3]
cpu
cpu


In [30]:
# Tensor to NumPy
import torch

tensor = torch.cuda.FloatTensor([1,2,3])
# 연산 그래프로부터 detach, .cpu()로 cpu로 보냄, .numpy()로 numpy 배열로 변환
ndarray = tensor.detach().cpu().numpy()
print(ndarray)
print(type(ndarray))

[1. 2. 3.]
<class 'numpy.ndarray'>
